import { SiteNav } from '@/components/site-nav'
import { SiteFooter } from '@/components/marketing/closing'

export default function TermsPage() {
  return (
    <main className="relative min-h-dvh">
      <SiteNav />
      <section className="relative mx-auto max-w-3xl px-6 pt-36 pb-24">
        <h1 className="text-balance text-4xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="mt-10 space-y-8 text-muted-foreground">
          <div>
            <h2 className="text-lg font-semibold text-foreground">Using Social.IQ</h2>
            <p className="mt-2 leading-relaxed">
              Social.IQ provides AI-generated analysis and suggestions based on conversations you
              submit. Results are generated by an AI model and are provided for informational and
              entertainment purposes — they are not professional relationship, psychological, or
              legal advice.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">Your content</h2>
            <p className="mt-2 leading-relaxed">
              You are responsible for the conversations and screenshots you upload. Do not submit
              content that isn't yours to share, or that violates another person's privacy or
              applicable law.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">Subscriptions</h2>
            <p className="mt-2 leading-relaxed">
              Paid plans renew automatically each billing period until cancelled. You can cancel
              anytime from your account settings; access continues until the end of the current
              billing period.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">Limitation of liability</h2>
            <p className="mt-2 leading-relaxed">
              Social.IQ is provided "as is." We do not guarantee any particular outcome from
              following suggestions generated by the app.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">Contact</h2>
            <p className="mt-2 leading-relaxed">
              Questions about these terms? Reach out at contact@socialiq.app.
            </p>
          </div>
        </div>
      </section>
      <SiteFooter />
    </main>
  )
}
